# Generated by Django 3.2 on 2023-07-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='Matematicas10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='math',
            name='Matematicas6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='math',
            name='Matematicas7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='math',
            name='Matematicas8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='math',
            name='Matematicas9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
