# Generated by Django 3.2 on 2023-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biology',
            name='Biology10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biology',
            name='Biology6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biology',
            name='Biology7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biology',
            name='Biology8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biology',
            name='Biology9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
